### ISSUE TITLE
Sony MZ-RH1 slow NetMD SP write speeds

### ISSUE THREAD

**Issue by dharmabumstead** [gavinbenda/platinum-md#111]
Sony MZ-RH1 performs SP write operations at roughly half the speed of a Sony MZ-N920.

**Comment by gavinbenda** [comment]
This has been discussed a bit recently on other forums.
From my testing I can confirm that Hi-MD players are slower in general at writing SP.

Seems the general consensus is that newer Hi-MD players are slower because the focus was on the Hi-MD capabilities.
It's very hard to test as there's no easy comparison using Sonic Stage as it's not full quality SP.

Certainly for any of the 'data' formats including LP2, newer players are a lot faster.
