### ISSUE TITLE
MZ-RH1 worked well one day (W10), after restart computer constantly negotiating

### ISSUE THREAD

**Issue by mavdt** [gavinbenda/platinum-md#41]
Installed Platinum-MD last week (windows 10), made about 6 MD's and was working well.
Today (a few days later) I tried it again and it won't recognize the MD again. Tried Zadig to install it again, but nothing helps. 
It is alway negotiating and never stops with it. What is the problem or what am I doing wrong.
Kind regards, Martin
![Sony MD-RH1](https://user-images.githubusercontent.com/66524343/83947732-2bc1ee80-a819-11ea-9b03-7974ed6a75d3.png)

**Comment by taquitos** [comment]
I'm facing the same issue (on a mac, though) with the same device: MZ-M200
I've attached my logs.
[Console.log](https://github.com/gavinbenda/platinum-md/files/4741184/Console.log)

**Comment by gavinbenda** [comment]
Just checking how you went with this? I think the reason it wasn't connecting is that it was trying to connect as a Hi-MD device, rather than a regular MD device.

I recently added some information to the troubleshooting section around this:

> If using a Hi-MD device, ensure that the device is set to MD mode (mainly if using a blank disc) Option then Disc Mode and select md.

https://github.com/gavinbenda/platinum-md#faq--troubleshooting

**Comment by taquitos** [comment]
Yes, that was the problem, sorry I forgot to drop a comment that what you suggest here is exactly the fix 😃
