### ISSUE TITLE
Blank window on Catalina

### ISSUE THREAD

**Issue by Shadester** [gavinbenda/platinum-md#77]
I have installed homebrew and also done brew install for the dependencies (followed the ones in the Readme.MD and not on https://platinum-md.app, since it's missing json-c).

I've dowloaded the build from the releases and when I run it, I see only an empty white window.

I've also tried running it from source and it's still a white window.

**Comment by gavinbenda** [comment]
Hey - if you are wanting to run the latest code, you will need to compile it from source, rather than download from the releases (as there's no build there with the latest code).

To install from source, you need to do (from terminal):
`git clone https://github.com/gavinbenda/platinum-md.git` then:
`cd platinum-md` and run:
`yarn && yarn run dev`

This will compile and launch the app using the latest build.

**Comment by Shadester** [comment]
Did the above command:

![blank screen](https://user-images.githubusercontent.com/869974/104139821-d0ce1800-5362-11eb-95ca-a295289da366.png)

**Comment by Shadester** [comment]
Ah! Now it worked. When I took out the player USB and inserted it again. But no error or anything is a bit confusing, tbh.

**Comment by gavinbenda** [comment]
Yep - non-tagged/released builds will likely still be in testing, and contain bugs. There has been some further work done on the reliability of connecting, so once that's tested/merged, hopefully will perform better!
